### ISSUE TITLE
Curious about the train_100.tsv

### ISSUE THREAD

**Issue by Punchwes** [najoungkim/COGS#1]
Thanks very much for your work @najoungkim  and I really like this evaluation. I've got some questions regarding your dataset.

I noticed that the **_hedgehog_** has been used for  **_the subj_to_obj_common_** task. In the train.tsv, you have one exposure example of hedgehog being used as subject but in train_100.tsv, your entire corpus does not contain the word hedgehog. Shouldn't the train_100.tsv have 100 examples of hedgehog as subject according to your description?

I am quite confused about this now, not sure what is the exact process of adding 100 exposure example. How can you be able to generalize hedgehog in the gen dataset when you have none existence of it in the train_100 set. (it seems that you remove some sentences from train.tsv? exposure_example_subj_common does not exist in train_100 anymore...)

(The same occurs in the obj_to_subj_common, where cockroach occurs in obj position once(and only once in the whole corpus) in train.tsv, and none in the train_100.tsv while cockroach is used to test obj_to_subj_common task)

Thanks very much for any response.

**Comment by najoungkim** [comment]
Hi @Punchwes,

Thanks for raising this issue. Quickly looking at it, it looks like I've uploaded a version that contains only the oversampled primitives (and not the exposure examples). So your confusion is totally justified---the file should really contain 100 examples with hedgehog in the subject position and 100 examples with cockroach in the object position. I'll try to push a fix this week.

Hope this addresses your question!

**Comment by Punchwes** [comment]
Thanks very much for your quick reply. Looking forward to the new train_100 dataset :)

**Comment by DualProblem** [comment]
Hi @najoungkim,

Spotted the same, wonder when will the correct dataset be uploaded. Thanks a lot for your great efforts!

**Comment by najoungkim** [comment]
Thanks for the reminder! Just replaced the dataset with the correct version. Looks like the old version actually did contain some of the exposure examples, just missing the ones for Subj -> Obj (proper/common), Obj -> Subj (proper/common). The new version should contain 400 additional examples that were missing.
